### ISSUE TITLE
Nested Rows support ?

### ISSUE THREAD

**Issue by mayanksahai** [react-component/table#101]
i am trying to check if component has support for nested rows or has concept of row grouping.
for example i have descriptor row and its value is some of its child rows: 

Light Motor Vehicles  ----- 9
 (-) Car   ---- 2
 (-) motorcycles --- 3
 (-) Add new Row --- 4

similar to what we can do in Excel ?.

**Comment by jlc467** [comment]
Take a look at http://react-component.github.io/table/examples/childrenIndent.html

For you, try something like:
```
/* eslint-disable no-console,func-names,react/no-multi-comp */
const React = require('react');
const ReactDOM = require('react-dom');
const Table = require('rc-table');
require('rc-table/assets/index.less');

const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  width: 400,
  render: (v, record) => {
    if (v === 'Add new row') return <a href="#">{v}</a>
    return v
  }
}, {
  title: 'Count',
  dataIndex: 'count',
  key: 'count',
  width: 100,
}];

const data = [{
  key: 1,
  name: 'Light Motor Vehicles',
  count: 9,
  children: [{
    key: 11,
    name: 'Car',
    count: 2
  }, {
    key: 12,
    name: 'motorcycles',
    count: 3
  },
  {
    key: 13,
    name: 'Add new row',

  }]
}];

function onExpand(expanded, record) {
  console.log('onExpand', expanded, record);
}

ReactDOM.render(
  <Table defaultExpandAllRows columns={columns} data={data} indentSize={30} onExpand={onExpand} />,
  document.getElementById('__react-content')
);
```

**Comment by mayanksahai** [comment]
Hi i was looking into Subtable example and have some issues incorporating
that into my app.

i have written service using spring-rest and service return response in
json format:


   1. Object
      1. content:Array[1]
         1. 0:Object
            1. content:Array[0]
            2. dateTime:Object
            3. links:Array[3]
               1. 0:Object
                  1. href:"http://localhost:8080/api/expenseReports/1"
                  2. rel:"self"
                  3. __proto__:Object
               2. 1:Object
                  1. href:"http://localhost:8080/api/expenseReports/1"
                  2. rel:"expenseReport"
                  3. __proto__:Object
               3. 2:Object
                  1. href:"
                  http://localhost:8080/api/expenseReports/1/children"
                  2. rel:"children"
                  3. __proto__:Object
               4. length:3
               5. __proto__:Array[0]
            4. name:"Dec month report"
            5. value:0



that is incompatible to format given in example:

[ { a: 'a1', }, { a: 'a2', b: 'b2', children: [ { a: 'a2-1', b: 'b2-1', },
{ a: 'a2-2', b: 'b2-2', }, ], }, { a: 'a3', c: 'c3', d: 'd3', }, ];


i think "links" in my response has to be named as "children" to make it
work.

1) do i need to transform response to match structure component expects
2) do you have any example for the same.

thanks

mayank
