### ISSUE TITLE
固定行

### ISSUE THREAD

**Issue by Vsion** [react-component/table#102]
- 固定行 
  表格上下固定行
 例:
    上: 提示行
    下: 汇总行

**Comment by yesmeck** [comment]
`上: 提示行`

这个跟固定表头有什么区别？

**Comment by afc163** [comment]
用 title 和 footer。

**Comment by Vsion** [comment]
首先是在表格里面 title 和 footer并满足需求
例:
现在有一个数据表格 
 - 上固定行(提示行):
    固定三行: 第一行每一列数据的分差 第二行每一列数据的均值 第三行每列数据的标准值 是进行对比
 - 下固定行(汇总行):
    每列数据的汇总行
所以你们只需要提供固定该行就行了, 规则写在render里面

**Comment by benjycui** [comment]
> 首先是在表格里面 title 和 footer并满足需求

???

所以是满足还是没满足？

**Comment by Vsion** [comment]
不满足, 莫名其妙少两个字 !不能!

**Comment by Vsion** [comment]
首先是在表格里面 title 和 footer并[不能]满足需求
例:
现在有一个数据表格

上固定行(提示行): 固定三行: 第一行每一列数据的分差 第二行每一列数据的均值 第三行每列数据的标准值 是进行对比
下固定行(汇总行): 每列数据的汇总行
所以你们只需要提供固定该行就行了, 规则写在render里面

**Comment by afc163** [comment]
建议控制数据自行实现吧，固定行不是一个业界通用的功能。

**Comment by Vsion** [comment]
逃避

**Comment by afc163** [comment]
我们人少事多，请多谅解。
