### ISSUE TITLE
Issue integrating with spring-rest response

### ISSUE THREAD

**Issue by mayanksahai** [react-component/table#104]
Hi i was trying to make use subTable example and consume data from spring -rest. my service returns the data in this format.
 
i followed this example: 
https://spring.io/guides/tutorials/react-and-spring-data-rest/

to create a rest data provider and inject its response into rc-table via Axios call.

rest response contains _embedded, _links and i guess rc-table component explicitly looks for "children"
sub element array to render subTable.

how can i translate incoming json response to fit into the world of sub-table example.

**Comment by yesmeck** [comment]
I'd recommend you to ask this question on StackOverflow.
