### ISSUE TITLE
有没有必要对表格的TableRow性能优化？

### ISSUE THREAD

**Issue by xiaoqqchen** [react-component/table#106]
有没有必要在TableRow中使用shallowequal或者immutable.js的is方法来优化表格的性能呢？
比如：
```js
const TableRow = React.createClass({
  ...
  shouldComponentUpdate(nextProps, nextState) {
    return !shallowequal(nextProps, this.props) || !shallowequal(nextState, this.state);
  },

}
```

如果一个页面的表格有成百上千行，任何一个state或者props改变都会触发每个TableRow的render，这个对整个页面的性能损失是很大的。
所以，有没有必要也对TableRow添加shouldComponentUpdate方法？

**Comment by yesmeck** [comment]
见： https://github.com/react-component/table/pull/96 https://github.com/react-component/table/pull/98

**Comment by yesmeck** [comment]
Table 的性能问题，欢迎在这里讨论 https://github.com/ant-design/ant-design/issues/2884
