### ISSUE TITLE
没有设置 `title` 的列，展示时表头变成了 `td`，应该是 `th`

### ISSUE THREAD

**Issue by RexSkz** [react-component/table#1066]
CodeSandbox 链接：https://codesandbox.io/p/sandbox/antd-biao-ge-lie-mei-you-title-shi-hui-bian-wei-td-er-fei-forked-yy2x6s?file=%2Fdemo.tsx%3A1%2C1

<img width="1193" alt="image" src="https://github.com/react-component/table/assets/27483702/a8e03e38-4d3c-4eee-83da-f476f752f5b2">

原因是 `src/Header/HeaderRow.tsx` 里面的 `component` 字段判断逻辑有误：

```tsx
<Cell
  component={column.title ? CellComponent : tdCellComponent}
/>
```

这不但会影响到 `title` 为空的列，也会影响到 `expandable` 所在列，因为它大部分情况下也没有 `title`。

**Comment by zombieJ** [comment]
要 blame 一下为什么这么写，感觉是有意为之

**Comment by RexSkz** [comment]
引入的 PR 是这个：https://github.com/react-component/table/pull/859

之前是正常的，这个 PR 专门让上层 `HeaderRow` 传了个 `tdCellComponent` 下来，并且在没有设置 `title` 时使用了它，应该是故意的。

查了一下 [WHATWG](https://html.spec.whatwg.org/multipage/tables.html#the-th-element) 没有强制规定 `thead` 里面必须如何使用 `th` 或 `td`，似乎也没有最佳实践之类的东西，所以我不知道为什么要这么改😂

**Comment by RexSkz** [comment]
这个 issue 跟链接中不是同一个场景：

链接里想表达的是：有一种场景叫做“第一列是表头列”。在这种场景下，左上角的单元格没有表头功能，展示为 `td` 比较合理。不过在 antd 里，这种场景用 `rowScope: 'row'` 就可以解决了。

没有 `title` 的表头不一定没有表头功能，例如：

<table>
<tr><th>Before</th><th>After</th><th></th></tr>
<tr><td>1</td><td>2</td><td>+1</td></tr>
<tr><td>3</td><td>4</td><td>+1</td></tr>
</table>

此外对于 `rowSelection`，如果设置为 checkbox 则左上角有内容、radio 则没内容，不能因为这个来推断“是否有表头功能”。
