### ISSUE TITLE
Provide a function onRowHover

### ISSUE THREAD

**Issue by hy2015** [react-component/table#107]
1. When mouse hover a row, I want to render a few buttons(edit/delete) to append to a row cell.

It can be implemented like below.

Change two functions of the file 'TableRow.jsx'

  onMouseEnter(event) {
    const { onHover, hoverKey, record, index, onRowHover } = this.props;
    onHover(true, hoverKey);                                                 //it's a inner function
    onRowHover(record, index, event);
  },

  onMouseLeave(event) {
    const { onHover, hoverKey, onRowHover } = this.props;
    onHover(false, hoverKey);
    onRowHover(null, null, event);
  },

**Comment by yesmeck** [comment]
@hy2015 Fell free to open a PR.

**Comment by czy0729** [comment]
这个我感觉通过给你放按钮的td一个hover css就可以实现了, 每次都render消耗不大吗

**Comment by agutoli** [comment]
https://github.com/react-component/table/pull/117

**Comment by handycode** [comment]
.setting {
     display: none
}
.ant-table-row:hover {
      .setting {
        display: block
      }
}

**Comment by yesmeck** [comment]
https://github.com/react-component/table/commit/0db582a75dfa119715eb4db8a59eacfca744c5a0
