### ISSUE TITLE
支持 rowspan 和 colspan

### ISSUE THREAD

**Issue by afc163** [react-component/table#11]
![](https://t.alipayobjects.com/images/rmsweb/T1T_JhXb0iXXXXXXXX.png)

**Comment by yiminghe** [comment]
... 你来搞下...

**Comment by afc163** [comment]
好。

**Comment by zhechang520** [comment]
代码呢?

**Comment by afc163** [comment]
```js
columns = [{
  title: '列一',
  dataindex: '',
  colspan: 3,
  render(value, record, index) {
    return {
      children: value,
      props: {
        colspan: 2,
        rowspan: 2
      }
    };
  }
}]
```

**Comment by afc163** [comment]
主要满足三种情况。

1. 表头占多行。

![](https://t.alipayobjects.com/images/rmsweb/T1zWtiXbBhXXXXXXXX.png)

2. 单元格占多行。

![](https://t.alipayobjects.com/images/rmsweb/T1oW4iXipcXXXXXXXX.png)

3. 单元格占多列。

![](https://t.alipayobjects.com/images/rmsweb/T1NX8iXl4kXXXXXXXX.png)

**Comment by yiminghe** [comment]
:+1:

**Comment by MarshallChen** [comment]
所以现在支持不支持表头占多行？看源码好像是不行？

**Comment by swxy** [comment]
请问假如需要做
<img width="174" alt="table" src="https://cloud.githubusercontent.com/assets/5645617/23153535/25fb0d20-f844-11e6-8674-9f47263b1314.png">
这样一个根据数据动态合并单元格的表格，我的理解是需要针对每一条数据动态设置`rowspan`的值？

**Comment by lee-my** [comment]
同问 ，比如表格数据是动态获取的 ，如何实现自动合并呢？
