### ISSUE TITLE
error cause by use lodash in rc-table@5.2.6

### ISSUE THREAD

**Issue by ShikiRyougi** [react-component/table#114]
@yesmeck  
Before rc-table@5.2.6, when no dataIndex is specified,  the first argument of function render(text, record, index) equals to record, but now it will be undefined. 
here's the change log https://github.com/react-component/table/commit/86c84dc92f57acca320ac8e89c5dbd3828ca6140

**Comment by yesmeck** [comment]
Though, IMO `undefined` is the correct behavior. But in order to not breaking exists codes, I'm going to change it to `record`. I'd recommend to not relay on this behavior, since it could be change in next major release.

**Comment by yesmeck** [comment]
Related issue https://github.com/mariocasciaro/object-path/issues/77

**Comment by yesmeck** [comment]
Release 5.2.7.
