### ISSUE TITLE
Misaligned fixed table headers when header text becomes long

### ISSUE THREAD

**Issue by pastelsky** [react-component/table#118]
<img width="694" alt="screen shot 2017-01-17 at 10 23 40 am" src="https://cloud.githubusercontent.com/assets/8946207/22008203/0d86c268-dc9f-11e6-9d70-62608116fe45.png">

Reproduced codepen sample:
http://codepen.io/pastelsky/pen/rjWxLp

**Comment by yesmeck** [comment]
Try setting a column width.

**Comment by pastelsky** [comment]
All the columns have a column width set. See here http://codepen.io/pastelsky/pen/rjWxLp

**Comment by yesmeck** [comment]
It's a little complex to fix this issue, you can give the first column more widths (106px in your example) as a workaround.

**Comment by yesmeck** [comment]
Going to close this, if you have good solution to fix this issue, welcome PR.
