### ISSUE TITLE
Suggestion: column render add dataSource parameter

### ISSUE THREAD

**Issue by swxy** [react-component/table#123]
有个需求需要使用自定义render，但发现render 只提供了 `value, record, index`三个参数，却无法直接获得传给表格的dataSource。问题不大，但总觉得传一个dataSource参数比较好，像js数组中的forEach, map 等都有。

**Comment by yesmeck** [comment]
用闭包就可以了吧。

**Comment by swxy** [comment]
@yesmeck 闭包是可以的，我使用bind传递参数，
```
renderTable() {
    let columns = [{
        title: "xxxx",
        dataIndex: "sss",
        render: this.customRender.bind(this, dataSource, 'sss')
    }];
    ....
}

// customRender 方法接受5个参数
customRender(dataSource, dataIndex, value, record, index) {
    ....
}
```
是否可以这样想，如果传了`value, index, dataSource`，通过使用`dataSource, index`是可以计算出`record`的，所以传`dataSource`相对`record`来说，功能更加强大一点。

**Comment by yesmeck** [comment]
@swxy 不知道你是在用 `antd` 还是直接用的 `rc-table`？

**Comment by swxy** [comment]
@yesmeck 用的是`antd`，发现`antd`中的表格用的是`rc-table`组件，所以我就在这块新建issue了。

**Comment by yesmeck** [comment]
`antd` 里的 `index` 是有歧义的（在分页、过滤或者排序后会发生变化），所以用 `dataSource` 和 `index` 不一定能找到正确的 `record`。不知道你用 `dataSource` 的场景是什么。

**Comment by swxy** [comment]
我需要做一个合并相同数据行的功能，
<img width="174" alt="table" src="https://cloud.githubusercontent.com/assets/5645617/23354569/be2ff4f8-fd0c-11e6-9324-d43bc6ac809d.png">
需要使用`index, dataSource`，依据数据项是否相同，来计算每一行数据是否应该合并。

**Comment by yesmeck** [comment]
建议你还是用 `bind` 的方式吧，就像我前面说的， `antd` 里因为有分页、筛选的功能，会导致最终在 `rc-table` 拿到的 `dataSource` 跟原来的不一样，产生歧义。
