### ISSUE TITLE
If the amount of data is large, rolling becomes difficult

### ISSUE THREAD

**Issue by wxa1048989080** [react-component/table#133]
If the amount of data is large, rolling becomes difficult, how？
如果数据量很大（超过10万），滚动变得很困难

**Comment by yesmeck** [comment]
不能用分页吗？

**Comment by paranoidjk** [comment]
..... 10万的列表是什么场景

**Comment by afc163** [comment]
后台分页比较合适吧。

**Comment by hitzzc** [comment]
同问，我们有个需求，600行，200列，渲染起来特别慢，试了下facebook的fixed-data-table，就没有问题

**Comment by hitzzc** [comment]
@afc163

**Comment by afc163** [comment]
@hitzzc 可以搞一个例子看看有什么优化空间，性能问题要慢慢优化。

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/2884

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/3789
