### ISSUE TITLE
Wrong <Row> height while using  "tree structure" and "fixed Columns" at the same time

### ISSUE THREAD

**Issue by Harx** [react-component/table#134]
possible reason：
while setting height value to the Fixed Column Table <row>, without considering the situation that table can also be "Display tree structure data in Table".

================

问题：当同时使用”固定列“和”树形结构“时，固定表格的单元格高度值不正确。

原因：
在于给固定列表格的行高赋值时，没有考虑到”树形结构“表格的情况吧。
于是也就没有区分父级行和子级行。

然后在给”固定列表格“的行高赋值时，依次只给父级行赋值了（[Table.jsx#L323](https://github.com/react-component/table/blob/master/src/Table.jsx#L323)），给子级行高赋值时同样没有关注到顺序（[Table.jsx#L373](https://github.com/react-component/table/blob/master/src/Table.jsx#L373)）。赋值与取值（[Table.jsx#L638](https://github.com/react-component/table/blob/master/src/Table.jsx#L638)）的顺序不一致，导致没有正确对应上。

需要区分父级和子级，才能正确同步原始表格和固定列表格的行高度。

**Comment by yesmeck** [comment]
可以提供一个可重现的在线 demo 吗？

**Comment by harekuer** [comment]
with the same problem,it's hard to provide an online demo.

**Comment by Butorchin-Dmitri** [comment]
Yea, have the same problem. If you try to render tree with hierarchy and apply the horizontal scrolling at the same time, and for example add a very long text into any column, the columns heights just are not good.

**Comment by yesmeck** [comment]
Should be fixed in the new version, ping me if the problem still exists.
