### ISSUE TITLE
Fixed columns are doubled when no other columns occur

### ISSUE THREAD

**Issue by Tomatosoup97** [react-component/table#138]
This occurs only when there are no other columns, but fixed ones.

Data provided:

```javascript
    const columns = [
      { title: 'title1', dataIndex: 'a', key: 'a', width: 100, fixed: 'left' },
      { title: 'title2', dataIndex: 'b', key: 'l', width: 100, fixed: 'right' },
    ];

    const data = [
      { a: '123', b: 'xxxxxxxx', d: 3, key: '1' },
    ];
```

Screenshot:
![doubled_columns](https://cloud.githubusercontent.com/assets/11841387/25527581/a0012fb0-2c19-11e7-92aa-8d1a53d127de.png)

**Comment by paranoidjk** [comment]
Please provide a reproducible demo.
http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Tomatosoup97** [comment]
I was fighting with codepen to run the demo with all of the dependencis but i gave up.

You can simply copy the data over to fixedColumns example:
https://github.com/react-component/table/blob/master/examples/fixedColumns.js

It turned out that this occurs not only when there are no other columns but fixed ones

E.g
```
const columns = [
  { title: 'title1', dataIndex: 'a', key: 'a', width: 100, fixed: 'left' },
  { title: 'title2', dataIndex: 'a', key: 'b', width: 100},
  { title: 'title3', dataIndex: 'b', key: 'l', width: 100, fixed: 'right' },
];
```
and same `const data` result in same issue

**Comment by yesmeck** [comment]
All columns are fixed are meaningless.
