### ISSUE TITLE
(Suggestion) Would consider add 'Overriding Default Elements' feature.

### ISSUE THREAD

**Issue by CrisLi** [react-component/table#139]
I am comparing **rc-table** and **reactabular**.

One of good feature of **reactabular** is that it can [Overriding Default Elements](https://reactabular.js.org/#/table/overriding-default-elements).

Would we consider add a similar feature. Then our table can apply any css framework or existing react component, such as react.semantic-ui.com and react-bootstrap.github.io

**Comment by paranoidjk** [comment]
I think `props.render` can be used to custom elemts, see https://github.com/react-component/table#column-props

**Comment by CrisLi** [comment]
@paranoidjk `props.render` only can custom the element inside the `td` (column).

The `reactabular` has better custom options.

```js
{
  components: {
    table: 'table',
    header: {
      wrapper: 'thead',
      row: 'tr',
      cell: 'th'
    },
    body: {
      wrapper: 'tbody',
      row: 'tr',
      cell: 'td'
    }
  }
};
```

**Comment by paranoidjk** [comment]
well, i see. But this feature seems not very high priority to us， so welcome PR.

https://github.com/react-component/table/blob/master/src/TableCell.jsx#L73
https://github.com/react-component/table/blob/master/src/TableHeader.jsx#L19
