### ISSUE TITLE
Scrolling in the XY box leaves the table head in the same place.

### ISSUE THREAD

**Issue by jinaq** [react-component/table#158]
This problem si in example: http://react-component.github.io/table/examples/scrollXY.html.
This problem is  Y-scrolling

**Comment by yesmeck** [comment]
Could you describe you issue more detailed?

**Comment by jinaq** [comment]
![error-scrollxy](https://user-images.githubusercontent.com/7011271/29983175-fbdf1f2e-8f54-11e7-80f5-e0a342ae4b34.png)

This problem is on linux mint, Chrome 60.0.3112.113, Firefox 55.0.2
