### ISSUE TITLE
Manage expanded rows externally

### ISSUE THREAD

**Issue by queimadus** [react-component/table#16]
As the library stands there is no way to control the expanded rows pragmatically (closing the expanded rows externally e.g.).

Do you plan on adding functionalities to allow this or do you rather keep this as internal state to keep the library simple?

**Comment by yiminghe** [comment]
maybe add a expandedRowKeys prop and normalize state to expandedRowKeys ?

welcome pr

**Comment by queimadus** [comment]
I'm ok with that. I'll work on the PR.

**Comment by yiminghe** [comment]
https://github.com/react-component/table/pull/17
