### ISSUE TITLE
How to use "expandedRowRender" to expand only those rows with children?

### ISSUE THREAD

**Issue by hui-w** [react-component/table#160]
I want:
- rows with children are expandable
- use my customized 'expandedRowRender' to render the children rows

However, the line 364 of "Table.jsx" makes all my rows expandable if I have "expandedRowRender" set:
`expandable={childrenColumn || expandedRowRender}`

Any suggestions?

Thanks.

**Comment by yesmeck** [comment]
Could you describe your question more detailed?
