### ISSUE TITLE
rowClassName should accept strings too, not just functions

### ISSUE THREAD

**Issue by terebentina** [react-component/table#162]
I am giving rows some default styles by using `rowClassName` like this:
```
<Table columns={this.columns()} data={alerts} rowKey="_id" rowClassName={() => styles.row} />
```

 It would be easier if `rowClassName` would accept strings as well:
```
<Table ... rowClassName={styles.row} />
<Table ... rowClassName="fooBar" />
```

**Comment by yesmeck** [comment]
PR is welcome.

**Comment by acamposruiz** [comment]
Hi @yesmeck , @terebentina, I have created a new PR to implement this feature!
You can check here https://github.com/react-component/table/pull/165

**Comment by terebentina** [comment]
Thanks guys, I tested this and it works ok. Much appreciated!

**Comment by acamposruiz** [comment]
It's my pleasure. Enjoy it!
