### ISSUE TITLE
Expand row by clicking on an Edit link, put form inside the expanded row.

### ISSUE THREAD

**Issue by llevar** [react-component/table#170]
I am trying to implement row editing when I have a cell with an Edit link. When I click the link the row expands and has a form inside the user can type into. I haven't been able to figure out how to trigger row expansion, nor how to get access to the expanded row element to slide a form field in there. I've tried to add the row index to expandedRowKeys, this opens up the row, but does not change the expandable icon, and still does not give me access to the row object. I want to retain the [+] icon so that when the users click it, the row expands without entering Edit mode.

**Comment by yesmeck** [comment]
Hello @llevar , could you demonstrate your issue on https://codesandbox.io ？

**Comment by llevar** [comment]
Hi @yesmeck , please see - https://92xmm6zvmo.codesandbox.io/

The idea is that the configuration column can have potentially a lot of data in JSON format, thus, when the user clicks on [+] the row should expand showing the full content of the configuration column inside. When the user clicks on Edit, the row should expand with a textarea inside the expanded row so that the user can insert the configuration content inside.

I'm observing two things here:

1. When I add a rowKey to the expandedRowKeys this does seem to expand the row visually, but it does not change the [+] icon to a [-] and does not fire the onExpand event.
2. When the Edit link is clicked, I'm not sure how to access the row within which this happens so that I can set its state, conditionally insert a textarea, etc.

Thanks.

**Comment by yesmeck** [comment]
1. `expandedRowKeys` should includes `rowKey`, not `index`, in your case, it's `workflows[0].key`,  and `rowKey` should be a string;
2. You already know which row is clicked, because you can access `record` in the `column[render]` function.

It's a usage question than a bug, I'm going to close this issue.
