### ISSUE TITLE
Feature request: resizable columns

### ISSUE THREAD

**Issue by abenhamdine** [react-component/table#173]
Hi, and thx for this pretty table component,

As far as I know, table columns are not currently resizable by the user.
It's a common feature in most datables, and it's particularly convenient when the length of content displayed in a column is unknown.

I found a resizable HOC for antd-table here :  http://www.yyframe.com/yycomponent/resizable-table/
(repo : https://github.com/77ircloud/yycomponent/tree/98e61cb76f741f11b705dbebd3367ea0c5589d5f/yycomponent/resizable-table)

but I think it would be better to include it in the library, given the common use.

**Comment by yesmeck** [comment]
http://react-component.github.io/table/examples/column-resize.html

Here is a example demonstrates how to  integrate rc-table with react-resizable. I'm not going to implement this as a built in feature.

**Comment by abenhamdine** [comment]
Ok thanks ! Looks like I missed to find this example.
Still seems a bit weird for me to not include such a common feature, but anyway, thx again and keep up this great work on react-component.
