### ISSUE TITLE
Has any method only to render specific changed table-cells rather than the whole table using rc-talbe? 

### ISSUE THREAD

**Issue by Tracis** [react-component/table#175]
I used rc-table to draw a table with many input tags. So the performance is poor.  Has any method only to render specific changed table-cells rather than the whole table?

**Comment by yesmeck** [comment]
Try overriding default elements, and adding a shouldComponentUpdate to the row component. Ref https://github.com/react-component/table/pull/171

**Comment by Tracis** [comment]
My rc-table is version 5.2.1. I want to know that which version starts to support 'components' props.

**Comment by yesmeck** [comment]
6.0.0
