### ISSUE TITLE
想咨询下tablerow.js中onHover方法是干什么的？

### ISSUE THREAD

**Issue by HuYuee** [react-component/table#176]
我在查看源码的时候发现onHover方法在table中，当column设置了fixed注册然后通过pops传入到tablerow中。

![image](https://user-images.githubusercontent.com/12147318/34189596-3e38fd2c-e577-11e7-85a1-8961bfc4d52e.png)

我发现只是在hover的时候重新渲染了该tablerow组件，并且加上了样式。但是样式的问题在css的:hover中已经实现了该功能。所以希望能知道下这一逻辑到底是否实现了其他功能？

![image](https://user-images.githubusercontent.com/12147318/34189635-6f0c949a-e577-11e7-9970-a17785eedca9.png)

![image](https://user-images.githubusercontent.com/12147318/34189529-d7f747a8-e576-11e7-84a0-d4356fb103b5.png)

**Comment by yesmeck** [comment]
有固定列的时候要把  hover 状态同步给固定列，因为固定列跟主表格是分开的两个表格。

**Comment by HuYuee** [comment]
明白了，多谢
