### ISSUE TITLE
How to upgrade rc-table version 5.2.1 to 6.1.1?

### ISSUE THREAD

**Issue by Tracis** [react-component/table#179]
I haved upgraded rc-table version 5.2.1 to 6.1.1 and replaced deprecated props from my code. But it still reported errors. 
![image](https://user-images.githubusercontent.com/7136882/34359117-219ff6d4-ea90-11e7-8dae-8be7c440d837.png)

**Comment by yesmeck** [comment]
This is not deprecated props.Can you reproduce it on https://codesandbox.io?
