### ISSUE TITLE
expandedRowKeys is mutated

### ISSUE THREAD

**Issue by terebentina** [react-component/table#180]
Trying to use `rc-table` with `expandedRowKeys`/`onExpandedRowsChange` in a `PureComponent` doesn't work because `expandedRowKeys` is mutated instead of a new copy being returned. This means that the component won't refresh after setting the state here:
```
  onExpandedRowsChange = (rows) => {
    this.setState({ expandedRowKeys: rows });
  };
```
You can see this problem even in your examples by changing the component to pure. 
The problem is probably here: https://github.com/react-component/table/blob/15f686204ec7d077f1e5afd4d24da31a79c6731d/src/ExpandableTable.js#L87 - I suspect `mini-store`'s `getState` doesn't return a copy.

My temp workaround for now is to create a copy myself:
```
  onExpandedRowsChange = (rows) => {
    this.setState({ expandedRowKeys: [...rows] });
  };
```

**Comment by yesmeck** [comment]
Thanks for reporting, fixed in 6.1.2

**Comment by aFatFlyingCat** [comment]
i have met the same problem in 6.2.1

**Comment by aFatFlyingCat** [comment]
when data changes, onExpandedRowsChange is triggered sevral times
