### ISSUE TITLE
alternative way to customize row props in 5.x?

### ISSUE THREAD

**Issue by Yuyz0112** [react-component/table#181]
I was using rc-table `v5.6.1` in my project, which does not has the `onRow` property to customize row props.

Since I found you have refactor the code in 6.x, I'm not quite sure whether there is some breaking changes or bundle size increasing in the new version, so I am wondering is there any alternative way to customize row props in 5.x? If not, how could I found more details about you code refactor which may help me to decide upgrade to 6.x or not.

Maybe I need to read some of the commits?

**Comment by yesmeck** [comment]
Upgrade.

**Comment by Yuyz0112** [comment]
Already upgraded to 6.x.
For anyone who used `ref` of Table in 5.x, it has been changed in 6.x.
```js
// 5.x
ref={ref => this.table = ref && ref.refs.bodyTable}

// 6.x
ref={ref => this.table = ref && ref.bodyTable}
```

**Comment by yesmeck** [comment]
I'd suggest don't rely on inner refs.

**Comment by yesmeck** [comment]
They are not public API.
