### ISSUE TITLE
Is there a way to show expandIcon partially?

### ISSUE THREAD

**Issue by ibio** [react-component/table#182]
My current project has a situation where only a few rows have expandable rows. I looked into `hasExpandIcon` at ExpandableRow.js and found out there's ALMOST no way to config this externally except passing `expandRowByClick` or I just don't know how to do it.

However, if I passed `expandRowByClick` and my custom expand button, it would still expand all rows including the rows which I intentionally do NOT want to be expanded, because those expandable rows are empty (I don't have data for those). Yes, I can remove the data in those empty expandable rows, **but the whole row will still receive toggle event and my custom expand button will response that**. I **only** want my custom expand button to toggle the expandable row :(

### My solution:
So I have to wrap this component again and pass `expandedRowKeys` to deal with my own expendable row logic. I can use this workaround but just feel a little bit hacky.

I'd like to hear your and other folks' opinion on this one. 

### To users:
Have you guys ever had this problem? If so, what's your solution?

### To authors:
Have you considered this scenario or is there another way to do it?

Thank all.

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/7817#issuecomment-344143155
