### ISSUE TITLE
Allow ExpandIcon to be overridden

### ISSUE THREAD

**Issue by hrgui** [react-component/table#186]
**Use case**
Need to use a different icon for the expand button.

**Ideas**

**Add a rendering method `expandCellRender`**
1. Add new property `expandCellRender`, PropTypes.Function that has the following props:  ` { prefixCls, expanded, record, needIndentSpaced }`
2. If `expandCellRender` is passed, then instead of rendering `ExpandIcon`, just call `expandCellRender`. https://github.com/react-component/table/blob/master/src/ExpandableRow.js#L69

advantage: allows flexibility 
disadvantage: requires work in rc-table

**Option 2, requires no work on rc-table**
- override rc-table-row-expand-icon rc-table-row-expanded and rc-table-row-expand-icon rc-table-row-collapsed via CSS

advantage: no work in rc-table
disadvantage: content is `text` only

**Comment by sytolk** [comment]
@hrgui do you have an example for Option: 2? How to override css classes used in react component

**Comment by hrgui** [comment]
Closing since its resolved in https://github.com/react-component/table/pull/236

**Comment by sytolk** [comment]
This fix not work with children
