### ISSUE TITLE
other table implementation

### ISSUE THREAD

**Issue by yiminghe** [react-component/table#19]
http://jspreadsheets.com/

http://zippyui.com/react-datagrid

https://handsontable.com/examples.html?headers

https://www.ag-grid.com/best-react-data-grid/

http://uxco.re/components/table/

http://adazzle.github.io/react-data-grid/

http://allenfang.github.io/react-bootstrap-table/

https://facebook.github.io/fixed-data-table/

https://reactabular.js.org

https://github.com/tannerlinsley/react-table

**Comment by yiminghe** [comment]
https://www.ag-grid.com/best-react-data-grid/

**Comment by yiminghe** [comment]
https://github.com/uxcore/uxcore-table

http://uxco.re/components/table/

**Comment by yesmeck** [comment]
http://allenfang.github.io/react-bootstrap-table/

https://facebook.github.io/fixed-data-table/

**Comment by yesmeck** [comment]
https://reactabular.js.org/#/column-definition/header

**Comment by jlc467** [comment]
http://blueprintjs.com/docs/#components.table-js [div based]
http://dev.office.com/fabric#/components/detailslist#Variants [div based]

**Comment by baochuang** [comment]
oisition: table/src/ColumnManager.js
code:  _cached = {}; 
    this._cache('isAnyColumnsFixed', () => {
      return this.columns.some(column => !!column.fixed);
    });
issuer: _cache is not a function, how does this code work?

**Comment by yesmeck** [comment]
@baochuang Please open a new issue.

**Comment by afc163** [comment]
https://github.com/tannerlinsley/react-table
