### ISSUE TITLE
Don't call onExpand when destroying

### ISSUE THREAD

**Issue by niba** [react-component/table#193]
In my application, I would like to remember expandedKeys between pages. Unfortunately, an `onExpand` method is called for every key when a component is about to get unmount and it's not possible to detect if onExpand has been called because some user clicked on it or because application decided to change page and reload components.
I don't think that application should call that method when destroying. It's very easy to do it yourself using react lifecycle methods.

**Comment by yesmeck** [comment]
Fixed in https://github.com/react-component/table/commit/242d249bde510c4ba64a47792fa5dccc71c65123
