### ISSUE TITLE
貌似现在的表格必须要有表头

### ISSUE THREAD

**Issue by simongfxu** [react-component/table#20]
现在项目中的需求：一个辅助表格，不需要表头。这个能否考虑支持？

**Comment by yiminghe** [comment]
useFixedHeader , 自己 css 隐藏掉头?

**Comment by simongfxu** [comment]
@yiminghe 可以倒是可以，就是比较蛋疼 :smile_cat: 
看了下代码应该加个配置项目，thead内不输出其他元素即可。

**Comment by simongfxu** [comment]
:+1:
