### ISSUE TITLE
Detail doucument  about Table onRow

### ISSUE THREAD

**Issue by liuyangc3** [react-component/table#202]
1 allowed properties name returned by `onRow` Func ?
```js
{
  onContextMenu :  function() {}
   ...
}
// or
{
  onRowContextMenu :  function() {}
   ...
}
```
2 what args need pass into  properties returned by `onRow` ?
```
<Table
  onRow={(record, index) => ({
    onContextMenu:  (????) => ()
  })}
```
an example in `readme` will be helpful

**Comment by yesmeck** [comment]
Result which `onRow` returned will pass to `tr`, so if you return a `onContextMenu` in `onRow`, basically it equals `<tr onContextMenu={() => {...}} />`.

PRs welcome.
