### ISSUE TITLE
ExpandableRow wasted too much

### ISSUE THREAD

**Issue by qhxin** [react-component/table#212]
I use My `PureTableRow` to check sCU, it works, but u can see `ExpandableRow` is not designed well and `TableCell` has been rendered too much , any way to solve it?

My table has over 200 rows and i'm not allowed to use pagination.

![wx20180622-094515](https://user-images.githubusercontent.com/8831920/41753781-1a81087c-7602-11e8-89ec-a5152028c8c6.png)

**Comment by yesmeck** [comment]
Could you reproduce your issue on https://codesandebox.io?
