### ISSUE TITLE
Pass className to header?

### ISSUE THREAD

**Issue by thisissami** [react-component/table#228]
Hello,

It seems that it's impossible to pass a `className` to a header in `Table`. You can pass a `className` to the `Table` as a whole (but if I target `thead` or `.ant-table-thead` within that, I can't change any of the styles there). 

I can pass a `className` to any row by using the `rowClassName` function.

There doesn't seem to be any way to target just the Header though... it seems really bizarre that anything in the table can be easily styled from within a component except for the header. Am I missing something here, or is this not possible with the current implementation?

Cheers, thanks for taking the time to read this!

**Comment by yesmeck** [comment]
You can pass `className` to `Table`, then style header with:

```javascript
<Table className="myTable" />
```

```css
.myTable thead {
  ...
}
```

**Comment by yesmeck** [comment]
Could you reproduce your issue on https://codesandebox.io?

**Comment by thisissami** [comment]
@yesmeck (and anybody else reading this in the future), I got it to work with the following code:

```javascript
import React from 'react';
import { Table } from 'antd';
import { css } from 'react-emotion';

const tableCSS = css({
  margin: '40px 120px',
  backgroundColor: 'white',
  '& table': {
    borderCollapse: 'collapse'
  },
  '& thead > tr > th': {
    backgroundColor: 'darkblue',
    color: 'white',
  },
  '& thead > tr': {
    borderWidth: '2px',
    borderColor: 'yellow',
    borderStyle: 'solid'
  }
});

const BatchList = ({ batch }) => (
    <Table
      className={tableCSS}
      dataSource={this.props.children}
      columns={this.props.columns}
    />
);
```

This CSS lets you control the header as a whole.

**Comment by JadeHayes** [comment]
Has this been answered?
```
.myTable thead {
  ...
}
```

Is also not working for me
