### ISSUE TITLE
table supports specified columns scroll

### ISSUE THREAD

**Issue by yiminghe** [react-component/table#23]
<img width="997" alt="2015-12-25 12 26 22" src="https://cloud.githubusercontent.com/assets/200876/11999849/f3ebf34c-ab02-11e5-9e80-e2e0f78d37ba.png">

**Comment by yiminghe** [comment]
这个效果最好： http://docs.spmjs.io/hermes-table/latest/examples/

或者先支持 scrollX:  http://www.datatables.net/examples/basic_init/scroll_x.html

**Comment by afc163** [comment]
两个解决的是同一个问题呀。

**Comment by afc163** [comment]
让设计层面先 PK 吧。

**Comment by benjycui** [comment]
OSX 把滚动条吃了，所以用户可能发现不了 `scrollX` 交互的存在。
