### ISSUE TITLE
render in Column should have access to all data, not just record...

### ISSUE THREAD

**Issue by chetanpan** [react-component/table#233]
Sometime it is necessary that to render  a cell, data in other rows are needed...
I would like it as follows:

render:  (text, record, records) => ...

Request you to provide access to records anywhere record is passed...

**Comment by yesmeck** [comment]
You are free to access all records by closure.

**Comment by chetanpan** [comment]
Sorry for late reply.

Closure is not available to me as I am creating columns in different module as library. This would allow me to reuse columns as library.

What else can be done?

**Comment by yesmeck** [comment]
You can achieve your requirement by creating a factory function:

```javascript
// moduleA.js
function createCustomRender(data) {
  return (text, record) => {
    ....
  }
}
```

```javascript
// moduleB.js
const columns = [{
 ...,
 render: createCustomRender(data),
}]
```
