### ISSUE TITLE
其他元素代替table时被包裹的colgroup元素出现warning

### ISSUE THREAD

**Issue by doubaozia** [react-component/table#238]
https://github.com/react-component/table/blob/cd5ad565eae6664bb801afa173c3d00ddef37310/src/BaseTable.js#L167

是否可以将BaseTable组件中加一个判断，如果components.table元素不为table的话不渲染ColGroup组件。

**Comment by yesmeck** [comment]
你把 `components.table` 设置成了什么？

**Comment by doubaozia** [comment]
> 你把 `components.table` 设置成了什么？

每一行设置为一个Card。

**Comment by yesmeck** [comment]
components.table 必须是或者返回一个 `table`
