### ISSUE TITLE
Add render prop in Table

### ISSUE THREAD

**Issue by sabarnix** [react-component/table#239]
I have a data which looks like this
`data: [{
    imports: {
        value: 1234,
        isActive: true,
        status: 'pending'
    },
    exports: {
        value: 2011,
        isActive: true,
        status: 'pending'
    }
}, {...}]`

The value for the cell is in the value key and it also contains some more metadata. Can we have prop renderRowCell which accepts component and calls the component with the data.

`function renderCell({ value: { value, isActive }, ...props }) {
  return (<td {...props} className={cx('active', isActive)}>{value}</td>);
}`

and then pass it to the table

`<Table data={data} columns={columns} renderRowCell={renderCell} />`

**Comment by zombieJ** [comment]
You can use `render` prop in `columns` def.
