### ISSUE TITLE
有无必要为 expandable: false 的行增加 expandIcon 的占位符

### ISSUE THREAD

**Issue by jaredleechn** [react-component/table#24]
增加了 indent 发现无法展开的行和可展开的行差了一个 expandIcon 的宽度，看起来很奇怪，如图 aa 和 ab

要不要为无法展开的行增加一个同等大小的占位符？

![image](https://cloud.githubusercontent.com/assets/5318333/12001389/9bcb5476-ab22-11e5-91d3-24074e340609.png)

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-expand

ant design 里的做法是图标单独一列。

**Comment by jaredleechn** [comment]
场景有点不太一样，antd 里的这个是通过 `expandedRowRender ` ，会触发 `expandIconAsCell`

这里的是直接通过数据里的层级关系 `data.i.children.i.children...` 来渲染，直接加 `{indentText}{expandIcon}` 在内容前面

而且这种数据自带层级的，如果把图标全放在同一列会不会比较奇怪

**Comment by benjycui** [comment]
这样子要把 icon 单独一列有点难
![image](https://cloud.githubusercontent.com/assets/3580607/12001704/12bc4b2a-ab29-11e5-9677-5489c56df9e2.png)

**Comment by jaredleechn** [comment]
现在解决方案是给没有 `children` 的节点增加占位的 icon，现在样式看起来很奇怪，是的，aba 和 aca 真的是对齐的

![image](https://cloud.githubusercontent.com/assets/5318333/12001965/f50f4fa4-ab2e-11e5-812a-61ffcf526190.png)
