### ISSUE TITLE
something wrong about rowSelection

### ISSUE THREAD

**Issue by m26597** [react-component/table#240]
I created a table with column selected function. When I choose a only one column with assigned with, the checkbox column would change its position:
                         
![default](https://user-images.githubusercontent.com/39291213/45398989-f6ef2a80-b678-11e8-8ae8-d21ef1cc93b2.png)

 But it would be normal when I choose a column without assigned width:
          
![Uploading 图片.png…]()

Please help

**Comment by m26597** [comment]
the second picture doesn't show below, it's :
   
![default](https://user-images.githubusercontent.com/39291213/45403394-aaade580-b68c-11e8-808f-934010ec3af8.png)

**Comment by zombieJ** [comment]
Pls provide an online reproduce for this: https://codesandbox.io/
