### ISSUE TITLE
does the component support column sorting?

### ISSUE THREAD

**Issue by seanbrookes** [react-component/table#34]
It's not clear from the documentation or examples.

I thought there would be a 'onColumnHeaderClick' method or something to hook up some sort logic but doesn't seem to be.

Any pointers or suggestions appreciated.

**Comment by seanbrookes** [comment]
looks like column:title is a React Node type and supports a button implementation so I'll start there.

**Comment by benjycui** [comment]
You can try [antd.Table](http://ant.design/components/table/#demo-head), which is based on rc-table.

**Comment by ilyaskarim** [comment]
@afc163, Does component support sorting now?

**Comment by juancarlosqr** [comment]
@ilyaskarim I didn't find any out-of-the-box sorting support, but I was able to add a basic sorting easily with the `onHeaderCell` column's prop. Something like:

```js
const [sortColumn, setSortColumn] = useState(null);
const [sortDirection, setSortDirection] = useState(SORT_ASC);

...

const addOnHeaderCell = (column) => ({
  onClick: () => {
    setSortDirection((currentSortDirection) =>
      currentSortDirection === SORT_ASC ? SORT_DESC : SORT_ASC
    );
    if (sortColumn !== column) {
      setSortColumn(column);
      setSortDirection(SORT_ASC);
    }
  },
});

...

const columns = [
  ...
  {
    title: "Title",
    dataIndex: "title",
    key: "title",
    onHeaderCell: () => addOnHeaderCell("title"),
  },
  ...
]
```

And sort your data base on`sortColumn` and `sortDirection` values
Hope it helps
