### ISSUE TITLE
请问下是否支持/兼容redux或者其他数据流呢？

### ISSUE THREAD

**Issue by monkindey** [react-component/table#36]
因为用**redux**数据流的话，action reducer等是分开的，并且是只维护一套state即store，但是如果
我的管理系统用到这个组件的话(基于redux数据流)，我如何整合到我的管理系统里面呢？看了你们官方的[antd table 模式](http://ant.design/docs/pattern/table)跟我们很类型，想请问您们在做这些[项目](http://ant.design/docs/practice/cases)的时候是如何去管理数据流的呢？

**Comment by afc163** [comment]
好像和组件没什么关系。
