### ISSUE TITLE
function components that return a class instance

### ISSUE THREAD

**Issue by sezanzeb** [react-component/table#368]
Hi, after upgrading some packages including React and Antd, the console prints the following error message:

```
The <HeadTable /> component appears to be a function component that returns a class instance. Change HeadTable to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `HeadTable.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
```

The same applies to BodyTable, ColGroup and TableHeader

rc-table 6.7.0, react 16.6.0 and newer, antd 3.22.2

**Comment by sezanzeb** [comment]
the react-hot-loader react-dom patch fixes it, but I can't tell at the moment if the issue was caused by react-hot-loader all along https://www.npmjs.com/package/react-hot-loader#hot-loaderreact-dom

**Comment by pitops** [comment]
@sezanzeb thanks this worked

**Comment by zhalice2011** [comment]
it not work for me , sad

**Comment by Silencewanghui** [comment]
`yarn add react-dom@npm:@hot-loader/react-dom`
It works for me.

**Comment by ClausClaus** [comment]
`npm install @hot-loader/react-dom@16  --save` work for me, thanks!

**Comment by arieltlm** [comment]
npm install react-hot-loader@4.12.14

**Comment by zhengyanwen** [comment]
`npm install @hot-loader/react-dom`

and webpack set：

```
resolve: {
    alias: {
      'react-dom': '@hot-loader/react-dom',
    }
}
```
