### ISSUE TITLE
RC-TABLE demo演示页显示异常

### ISSUE THREAD

**Issue by junxiongchu** [react-component/table#407]
地址： http://react-component.github.io/table/?selectedKind=rc-table&selectedStory=column-resize&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fsource%2Fpanel

切换到column-resize时页面报错。

undefined is not an object (evaluating 'nodeOrComponent.prototype.render')
    http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:17:23691
http://react-component.github.io/table/main.996c1c055eb967adaff5.bundle.js:1:35907
Ih@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:59785
ni@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:67081
fk@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:90445
Zj@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:90374
Lj@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:87742
Rg@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:84518
rk@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:112356
http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:113589
ck@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:88079
zk@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:56:113574
http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:40:21268
http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:36:132730
renderUI@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:36:132888
dispatch@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:36:146171
http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:36:131492
forEach@[native code]
value@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:17:70309
value@http://react-component.github.io/table/vendors~main.996c1c055eb967adaff5.bundle.js:36:156739
value@[native code]

**Comment by huepf** [comment]
Header says: Demo page is not working
