### ISSUE TITLE
table 的 columns 的 width 属性某些情况下不起作用? 

### ISSUE THREAD

**Issue by forbreak** [react-component/table#45]
如果单元格里面的内容是一个很长的英文字符串，中间没有空格等，这个字符串长度超过了 cloumns的定义的width 宽度，表格的列宽度就无法起作用。
后面我在样式中增加了 word-wrap:break-word;  就可以了。

**Comment by benjycui** [comment]
这个是浏览器默认的行为。

**Comment by afc163** [comment]
这个没办法，`word-wrap:break-word;` 是侵入性的行为，交由业务自行控制比较合理。
