### ISSUE TITLE
rc-table remounting rows on move causes react-dnd errors

### ISSUE THREAD

**Issue by jfangrad** [react-component/table#451]
Hello, I am attempting to use React-dnd with rc-table and am running into an issue when trying to implement the [simple example from react-dnd](https://react-dnd.github.io/react-dnd/examples/sortable/simple) using rc-table. In this example the rows are actually moved during the drag operation instead of just having a simple line indicate where the row will be dropped like the [standard dnd example for rc-table](http://react-component.github.io/table/?path=/story/rc-table--react-dnd).

However it appears that rc-table is unmounting and remounting rows when the update occurs which causes react-dnd to throw the error seen below:
![image](https://user-images.githubusercontent.com/11445215/78680853-03218500-78ba-11ea-8137-932cdcd7c09b.png)
Seems to me that the unmounting and remounting is causing react-dnd to lose some sort of reference to the dragged item.

Dragging the item works fine but this error is thrown each time the move operation is done and the error cannot be caught by react due to it occurring within a drag event handler.

A codesandbox which reproduces the issue can be found here:
[![Edit rc-table & react-dnd](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rc-table-react-dnd-3ci8t?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jfangrad** [comment]
No longer using this approach for my project.

**Comment by kliments** [comment]
Hello jfangrad,
In my project, I need to combine rc-table with react-dnd as well, but I have hit a wall and cant continue any further. Any possibility that you can share your new approach with me?
That would be great.
Thanks in advance :)
