### ISSUE TITLE
BUG：固定列表格阴影在IOS下显示一条竖线

### ISSUE THREAD

**Issue by shangdev** [react-component/table#454]
使用官方示例就可以复现：http://react-component.github.io/table/iframe.html?id=rc-table--fixedcolumnsandheader

复现步骤：从IOS下任一浏览器打开，如图固定列阴影部分会出现一条竖线：
![image](https://user-images.githubusercontent.com/15621520/79033416-b81cb000-7be0-11ea-9548-b43110a412fb.png)

IOS设备信息：Iphone7, IOS13.4

**Comment by imhxc** [comment]
该问题已知，在某些版本的 safari 浏览器下会出现该 bug（但是好像并不是必现）。
该阴影是由一个伪元素创建的，您可以临时将该阴影的宽度为 30px 来解决这个问题。

**Comment by shangdev** [comment]
@imhxc
