### ISSUE TITLE
Access nested properties with dataIndex

### ISSUE THREAD

**Issue by queimadus** [react-component/table#46]
Have you considered using something like https://github.com/mariocasciaro/object-path to parse `dataIndex`?

```js
const data = [{
  name: "John", 
  age: 25 , 
  custom: {
    one: 1, 
    two: 2
  }
}]

const columns = [{
  title: "Name",
  dataIndex: "name"
}, {
  title: "Age",
  dataIndex: "age"
}, {
  title: "My custom property one",
  dataIndex: "custom.one"
}, {
  title: "My custom property two",
  dataIndex: "custom.two"
}]
```

Name | Age | My custom property one | My custom property two
------------ | ------------- | ------------- | -------------
John | 25 | 1 | 2

**Comment by benjycui** [comment]
Or https://github.com/benjycui/exist.js 😅

**Comment by afc163** [comment]
https://github.com/75lb/object-get

**Comment by afc163** [comment]
PR welcome~ @queimadus

**Comment by bodfaj13** [comment]
This should help
```https://ant.design/components/table/#Migrate-to-v4```

**Comment by khanakia** [comment]
I cannot sort the tables anymore because it sends the fields like this now
`sortField: ["serviceType", "title"] `
but I need it to the like this
`sortField: ["serviceType.title"]`

So how to do that ???

**Comment by haniamine** [comment]
I tried a lot of things but currently the only one that worked for me is using a "**render**" instead of
 "dataIndex" at the columns.
`render: (record) => record.object.attribute`

so i'm suggesting this:

```
const data = [{
  name: "John", 
  age: 25 , 
  custom: {
    one: 1, 
    two: 2
  }
}]

const columns = [{
  title: "Name",
  dataIndex: "name"
}, {
  title: "Age",
  dataIndex: "age"
}, {
  title: "My custom property one",
 render: (record) => record.custom.one
}, {
  title: "My custom property two",
render: (record) => record.custom.two
}]
```

**Comment by khanakia** [comment]
> I tried a lot of things but currently the only one that worked for me is using a "**render**" instead of
> "dataIndex" at the columns.
> `render: (record) => record.object.attribute`
> 
> so i'm suggesting this:
> 
> ```
> const data = [{
>   name: "John", 
>   age: 25 , 
>   custom: {
>     one: 1, 
>     two: 2
>   }
> }]
> 
> const columns = [{
>   title: "Name",
>   dataIndex: "name"
> }, {
>   title: "Age",
>   dataIndex: "age"
> }, {
>   title: "My custom property one",
>  render: (record) => record.custom.one
> }, {
>   title: "My custom property two",
> render: (record) => record.custom.two
> }]
> ```

You are giving the solution to render the value. But I was talking about sortField when you click on the Sorting Icon in Table Header then it sends the value like that as I said above.

**Comment by haniamine** [comment]
@khanakia For sorting it's the same thing, you need to add sorter to columns:

```
{
    title: "My custom property one",
    sorter: (a, b) => a.custom.one-b.custom.one,
    render: (record) => record.custom.one,
  }
```

if your column had string values: 

`sorter: (a, b) => a.custom.one.localeCompare(b.custom.one),
`

**Comment by khanakia** [comment]
Ah, i see. I will give it a try. :) Thanks

**Comment by rikinshah23** [comment]
How to approach when trying to render an image? 
I am trying below but its not showing image. 

[  const columns = [
    {
      title: 'image',
      dataIndex: 'notificationImage.url',
      key: 'notificationImage.url',
      render: (record) =>
      //console.log(text, record && record.notificationImage && record.notificationImage.url, index)
      {
        record && record.notificationImage &&
          <img
            width="460" height="345"
            src={record.notificationImage.url} />
      }
    },](url)

**Comment by khanakia** [comment]
You are doing wrong. Do this way

```
const columns = [
  {
    title: 'image',
    dataIndex: ['notificationImage', 'url'],  // This is what changed
    key: 'notificationImage.url',
    render: (record) =>
    //console.log(text, record && record.notificationImage && record.notificationImage.url, index)
    {
      record && record.notificationImage &&
        <img
          width="460" height="345"
          src={record.notificationImage.url} />
    }
  },]
```

**Comment by rikinshah23** [comment]
@khanakia Thanks. That worked!

**Comment by rajkumarWebelight** [comment]
What when you search data {firstName+lastName}

**Comment by fridolinf** [comment]
sorry may i ask. how to display it if the row name is the same, if i match it it will output like this
![image](https://user-images.githubusercontent.com/50565864/120892265-9fb6f280-c637-11eb-8967-5a00c66a5548.png)

**Comment by khanakia** [comment]
@fridolinf it seems record.product is NULL please double check the DATA you are passing to the table.

**Comment by fridolinf** [comment]
> @fridolinf it seems record.product is NULL please double check the DATA you are passing to the table.

thank you for answering my question. I solved the problem
![image](https://user-images.githubusercontent.com/50565864/120895290-78b3ed00-c646-11eb-9410-2c7931969618.png)
