### ISSUE TITLE
support sorting by multiple columns?

### ISSUE THREAD

**Issue by liangqing** [react-component/table#54]
suppose we have three columns:

| Country | City | Name |
| --- | --- | --- |
| China | Shanghai | Zhang San |
| USA | New York | Jack |
| China | Beijing | Li Si |
| USA | LA | Rose |
| China | Shanghai | Wang Wu |

sort it by "Country", and then "City", "Name", after the sort, the table becomes:

| Country | City | Name |
| --- | --- | --- |
| China | Beijing | Li Si |
| China | Shanghai | Wang Wu |
| China | Shanghai | Zhang San |
| USA | LA | Rose |
| USA | New York | Jack |

**Comment by yesmeck** [comment]
`rc-table` don't have a built-in filter, you achieve it by define a custom title and filter the data on yourself.
