### ISSUE TITLE
Сan't see code examples from your github.io

### ISSUE THREAD

**Issue by midnightfim** [react-component/table#557]
![image](https://user-images.githubusercontent.com/47338393/100463639-35982080-30dd-11eb-8c74-94a710fb2f73.png)
Hey. 

I don't know if it's worth writing it here, but I can't see the code examples from your site. 

For vertical scrolling to appear, I have to go into the console and manually remove the `owerflow: hidden` value on the `<pre>` element. 

Please look at this bug. Thanks

**Comment by xrkffgg** [comment]
The current website has this problem, you can find code in https://github.com/react-component/table/tree/master/examples .

Soon, we will adopt another approach. Please pay attention.
