### ISSUE TITLE
table has default red border

### ISSUE THREAD

**Issue by u9646** [react-component/table#584]
hi,

why table has default red border

The online demo too: https://table.react-component.vercel.app/demo/class-name

**Comment by colshacol** [comment]
Why was this closed? This is a pain in the butt lol. There is no practical need for this to ship with red borders by default.

**Comment by yoyo837** [comment]
It's just a demo.

**Comment by colshacol** [comment]
The red border exists when I import and use rc-table.

**Comment by yoyo837** [comment]
How do you import `assets/index.less` or `assets/index.css`?

**Comment by yoyo837** [comment]
I think you should not use them, these are just to get the class name and for examples or docs.
