### ISSUE TITLE
summary is not a function!

### ISSUE THREAD

**Issue by cx690** [react-component/table#630]
antd v4.16.1,sometimes summary will be false.

```
 ...
 // Footer (Fix footer must fixed header)
 const summaryNode = summary?.(mergedData);
 const fixFooter =
   (fixHeader || isSticky) &&
   React.isValidElement(summaryNode) &&
   summaryNode.type === Summary &&
   (summaryNode.props as SummaryProps).fixed;
  ...
```

so  summary?.(mergedData); will throw an error: summary is not a function!

**Comment by yoyo837** [comment]
来个复现

**Comment by yoyo837** [comment]
提到antd

**Comment by cx690** [comment]
![aa](https://user-images.githubusercontent.com/37604988/120766390-ca784c80-c54c-11eb-90cf-888b24aecd23.png)
![cc4](https://user-images.githubusercontent.com/37604988/120766481-debc4980-c54c-11eb-8115-3d537c5cb23a.png)
![aa55112](https://user-images.githubusercontent.com/37604988/120766519-e4199400-c54c-11eb-9f9c-359097cae431.png)
rc-table v7.15.2  antd v4.16.1
之前版本是没有问题的，这两天antd版本升级后就挂了。
以前你写的是：const footerTable = summary && <Footer>{summary(mergedData)}</Footer>;
现在是：const summaryNode = summary?.(mergedData);
这个 false?.() 会报错 false is not a function哦。

**Comment by cx690** [comment]
项目内其他成员书写类型问题，加上这里更改了执行方式，升级后，报错
