### ISSUE TITLE
横向滚动条状态变更时，固定列阴影显示异常

### ISSUE THREAD

**Issue by lanten** [react-component/table#646]
[示例代码](https://codesandbox.io/s/charming-chaplygin-xp432?file=/src/App.js)

由 antd 定位到这里。
相关issuse：https://github.com/ant-design/ant-design/issues/31319

分析代码后发现，主要是由于数据变更时未刷新横向滚动条状态导致的。
https://github.com/react-component/table/blob/e26c5526f4b8ecc2c93bacc8237ad6218c2f1560/src/Table.tsx#L497-L501

将上面引用的代码作以下调整（在 `useEffect` 中添加 `data`订阅 ），似乎可以解决这个问题。
```tsx
  React.useEffect(() => {
    if (horizonScroll) {
      triggerOnScroll();
    }
  }, [horizonScroll, data]);
```

请评估影响，没有问题的话，稍后我将发起PR

**Comment by afc163** [comment]
PR is welcome
