### ISSUE TITLE
Data updated from outside are not updated

### ISSUE THREAD

**Issue by adammockor** [react-component/table#67]
If I update value of some key inside data array, relevant data cell isn't updated with new value.

When I commented out shouldComponentUpdate inside `TableCell.jsx` everything works just fine.

**Comment by benjycui** [comment]
Just create a shallow copy and pass it to `Table` after you modify `dataSource`。

**Comment by adammockor** [comment]
I am doing that like: (simplified use case)

```
import React from 'react';
import RcTable from 'rc-table';

class Table extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: props.data,
      columns: props.columns,
    };
  }

 render() {
    const columns = [...this.state.columns];
    const data = [...this.state.data];
   
    return (<RcTable
      columns={columns}
      data={data}
    />);
 }
}
```

**Comment by benjycui** [comment]
So, this may work.

**Comment by adammockor** [comment]
Yeah, but sadly don't. I was suspicious, that data state is mutated somewhere inside `Table.jsx`, but I can't find what is wrong.

**Comment by afc163** [comment]
```jsx
const a = { key: 'value' };
const data = [a];

const newData = [...data];
newData[0].key = 'new value';

console.log(data[0].value); // new value
```

https://github.com/ant-design/ant-design/commit/abecc44d38cc91e7ac50e755a1b9985ddd79fcd0

**Comment by afc163** [comment]
```jsx
const a = { key: 'value' };
const data = [a];

const newData = [...data];
newData[0] = { ...data[0] };

console.log(data[0].value); // value
```

**Comment by adammockor** [comment]
I was mutating data like this:

```
setRowChecked(value, id) {
    const data = this.state.data.map((item) => {
      if (item.id === id) {
        item.checkbox = value;
      }
      return item;
    });

    this.setState({
      data,
    });
  }
```

And I forgot about that `item` inside map function has still same reference, so map function creates new array but actual objects inside are not new. `return { ...item }` fixes my problem.

Thank you for your help. Nice lib by the way!
