### ISSUE TITLE
Expose click event in onRowClick

### ISSUE THREAD

**Issue by adammockor** [react-component/table#70]
Currently onRowClick expose `Function(record, index)`, but there should be original click event as third parameter `Function(record, index, event)`.

Example use case is filtering row clicks based on click target.

I can PR this if you agree with this behaviour.

**Comment by afc163** [comment]
:+1: PR welcomes ~

**Comment by JoshOY** [comment]
@adammockor 
Just looking for an issue like this, thanks~
(Yesterday I was wondering how to implement multiple row selection by shift + mouse clicking but I didn't found original click event API for onRowClick property)
