### ISSUE TITLE
在不同电脑上 table 滚动条的样式不同

### ISSUE THREAD

**Issue by suedar** [react-component/table#708]
在某些电脑上是占用内容区的
![image](https://user-images.githubusercontent.com/18492953/143840091-414c3684-0d4a-40c3-9722-a145410738bb.png)

在某些电脑是飘着的
![image](https://user-images.githubusercontent.com/18492953/143840222-4ad9e9c7-4c27-45f9-bdc9-532d511acf4c.png)

但是没有设置任何关于scrollbar的css，有人知道是为什么吗，非常感谢

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/143840661-c1f70808-ca2e-4cfc-ab4d-7deea8649283.png)

这个设置有关好像

**Comment by suedar** [comment]
@yoyo837 感谢大佬
