### ISSUE TITLE
表头行合并(Grouping columns)

### ISSUE THREAD

**Issue by yesmeck** [react-component/table#73]
现在表头已经可以列合并了，不知道有没有考虑过行合并？

我大概看了下代码，感觉按现在的 API 设计通过 rowspan 去做合并会比较难实现，是不是可以参考[ag-grid](https://www.ag-grid.com/javascript-grid-grouping-headers/index.php)的设计，比如要实现下面这样的表头合并：

<table>
  <thead>
    <tr>
      <th rowspan="2">姓名</th>
      <th colspan="2">其它</th>
    </tr>
    <tr>
      <th>年龄</th>
      <th>住址</th>
    </tr>
  </thead>
</table>

可以写成这样：

```javascript
const columns = [{
  title: '姓名',
  dataIndex: 'name',
}, {
  title: '其它',
  children: [
    {
      title: '年龄',
      dataIndex: 'age',
    }, {
      title: '住址',
      dataIndex: 'address',
    }
  ]
}];
```

**Comment by afc163** [comment]
这个需求确实在考虑了 https://github.com/ant-design/ant-design/issues/1430

你的建议看上去不错，可以尝试。
