### ISSUE TITLE
render组件通过函数调用报错，上一个版本没问题

### ISSUE THREAD

**Issue by cwjTerrace** [react-component/table#756]
```javascript
function TempCom(props) {
  const [state, setState] = React.useState(props.name);
  React.useEffect(() => {
    setTimeout(() => {
      setState('222222');
    }, 1000);
  }, []);
  return <div {...props}>{state}</div>;
}

const columns = [
  {
    title: 'name',
    dataIndex: 'name',
    width: 100,
    ellipsis: {
      showTitle: false,
    },
    render: (name: string) => TempCom({ name }), // 这种写发上个版本可以使用，最近发布之后报错了
    // render: (name: string) => <Aaaa />, // 这种写法没问题
  },
];
```
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/29698222/155098715-90964a30-42bb-4554-bee1-abab43258eb0.png">
这个commit引起的
https://github.com/react-component/table/commit/2bb803e0f03f2e417c89c56ee031b199abf72b81

**Comment by afc163** [comment]
@zombieJ 看看这个

**Comment by zombieJ** [comment]
不要依赖内部组件的生命周期，你的代码里如果用到 Hooks 就要用自己的上下文：
https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-8-forked-uum0tg?file=/index.js

`<TempCom />` 为 `React.createElement(TempCom)` 会创建自己的上下文，`TempCom(xxx)` 相当于做了一个 hooks 注入到 Cell 的上下文里，这不 React。
