### ISSUE TITLE
数据变化导致 columns 定义的 render 不会重新执行

### ISSUE THREAD

**Issue by zmGitHub** [react-component/table#81]
使用时发现, 我改变了数据状态 引起 render 渲染 但是在 columns 字段里定义的 render 是不会重新执行的 使用如果要在 table 里实时反应出来 columns 字段必须定义在 render 方法里面 这个问题不知道 不知道大神是怎么解决的
![image](https://cloud.githubusercontent.com/assets/6838405/18078889/7b0d7d56-6ec0-11e6-8855-c56ae583326e.png)

但是写在 render 函数里就 OK 了

**Comment by afc163** [comment]
图挂了。看描述，你需要学习下 react 生命周期。
