### ISSUE TITLE
多表头 IE9 下的问题

### ISSUE THREAD

**Issue by benjycui** [react-component/table#89]
好像是中间 table 的 th 高度没有同步到两边的 fixed table

![image](https://cloud.githubusercontent.com/assets/3580607/18772336/8f93e510-8178-11e6-978c-873c677a1423.png)

**Comment by afc163** [comment]
@yesmeck 来看下？

**Comment by yesmeck** [comment]
手头暂时没有 IE9，@benjycui  看看 #87 可以修正这个问题吗？

**Comment by yesmeck** [comment]
😢 发现跟 fixed column 合用的时候有不少问题

**Comment by yesmeck** [comment]
我周末再看看

**Comment by yesmeck** [comment]
![screen shot 2016-09-26 at 12 11 33 am](https://cloud.githubusercontent.com/assets/465125/18816495/dd1e61fa-837d-11e6-98ca-0463c72d83d1.png)


 #87 合并后应该可以了。

**Comment by yesmeck** [comment]
另外这里 https://github.com/ant-design/ant-design/blob/master/site/theme/static/template.html#L11-L14 IE9 是由 console 的，我在 IE9 下 console.log 了半天没效果，后来发现是这个 console-polyfill 的缘故。

**Comment by benjycui** [comment]
https://github.com/paulmillr/console-polyfill/blob/master/index.js#L17

IE9 下 `typeof console.log` 和 `Object.prototype.toString.call(console.log)` 都为 `Object`。。。

**Comment by benjycui** [comment]
合并了这个 PR 的 5.0.3 还是有问题。。。

**Comment by yesmeck** [comment]
@benjycui 你是在哪里看的？我在本地跑 antd demo 的时候发现 table 的那个 ajax demo 因为在 IE9 下不能跨域报错会导致表头合并的例子有问题。

**Comment by benjycui** [comment]
嗯，是 ajax 那个例子导致的问题，那这个  issue 关了。
