### ISSUE TITLE
改用 div 实现

### ISSUE THREAD

**Issue by yesmeck** [react-component/table#90]
现在比较麻烦的地方就是目前因为是用 `table` 标签实现的，所以 fixed column 的实现比较 tricky。然后导致一些功能比较难实现，比如 #83，然后 fixed column 跟其他功能同时使用的时候也很容易有 bug，比如 https://github.com/ant-design/ant-design/issues/3096 https://github.com/ant-design/ant-design/issues/3190 。

@afc163 觉得怎么样？

**Comment by afc163** [comment]
div 会丢失 table 原生的渲染布局，建议不要用。

**Comment by yesmeck** [comment]
我的想法是把 div 的 display 设置成`table-row`,`table-cell`。

**Comment by afc163** [comment]
你可以尝试一下，但感觉重写工作量会比较大~

**Comment by benjycui** [comment]
这里有些时用 `div` 实现的 https://github.com/react-component/table/issues/19

**Comment by benjycui** [comment]
@afc163 用 CSS 的 `display: table|table-row|table-cell` 应该能保证自动布局？

**Comment by benjycui** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/display#Values

**Comment by yesmeck** [comment]
简单用 div 实现了下，`display: table|table-row|table-cell`其实是没法用的，如果一个 div 用了`display:table-cell`的话，这个 div 就跟 `td` 没区别了，其他几个同理，这样的话 fixed-columns 还是不好搞，因为 fixed-columns 是需要把表格纵向切开来，但是 table 标签本身是以行的形式展示数据的。

**Comment by afc163** [comment]
现有的固定列实现，基本上参考自：https://datatables.net/extensions/fixedcolumns/ 目前市场上找到细节最好的实现。

**Comment by yesmeck** [comment]
另外我想了下，如果要做拖拽的话可能确实是用现在的实现会好一点。

**Comment by yesmeck** [comment]
还是保持现状这样吧，现在的问题不在这里了。
