### ISSUE TITLE
Expand all row initially not working

### ISSUE THREAD

**Issue by kevalbhatt** [react-component/table#93]
[I saw one example ](http://react-component.github.io/table/examples/expandedRowRender.html) for expand and collapse but it works only after render if I am not wrong ( expandedRowKeys={[0,1,2]} )  

Actually I want to show all row expanded initially  so I tried expandedRowKeys={[0,1,2]} props but it wan't worked.

Then I also tried defaultExpandAllRows={true} but that also not worked.

**Comment by yesmeck** [comment]
Could you post your code?

**Comment by kevalbhatt** [comment]
@yesmeck I found issue why defaultExpandAllRows is not working.

In data object key is not unique so is it possible to create key from your side if user not provide key in data object?

**Comment by yesmeck** [comment]
Will do generate keys based on index of data if no rowKey given. https://github.com/react-component/table/blob/master/src/Table.jsx#L175-L181

**Comment by kevalbhatt** [comment]
This is my code 

    class AssesmentTable extends Component {
    render() {
    const {routes, strandData} = this.props;
    const columns = [
      {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        width: 300,
        fixed: 'left'
      }, {
        title: 'Age',
        dataIndex: 'age',
        key: 'age'
      }, {
        title: 'Address',
        dataIndex: 'address',
        key: 'address'
      }
    ];

    const data = [
      {
        name: 'Jack',
        age: 28,
        address: 'some where',
        children: [
          {
            name: 'a2-1',
            b: 'b2-1'
          }, {
            name: 'a2-2',
            b: 'b2-2'
          }
        ]
      }, {
        name: 'Rose',
        age: 36,
        address: 'some where'
      }
    ];
    /*  take out everything required from props */

    return (
      <div className="panel-body">
        <Table columns={columns} style={{
          width: 800
        }} data={data} expandIconAsCell={true} defaultExpandAllRows={true} scroll={{
          x: 1200
        }}/>
      </div>
    );
    }
    }

now I click on plus button it want open and even its not expanded by default.

Warning which I saw in console.

Warning: flattenChildren(...): Encountered two children with the same key, `0`. Child keys must be unique; when two children share a key, only the first child will be used.

**Comment by yesmeck** [comment]
Yes, It's confusing now, you can set `rowKey` by yourself.

**Comment by amitkverma** [comment]
`expandedRowKeys` must be unique to `defaultExpandAllRows`  to work

**Comment by ChunKwangho** [comment]
<Table columns={columns} style={{
      width: 800
    }} data={data} expandable={{expandIconAsCell:true,
defaultExpandAllRows:true}}  scroll={{
      x: 1200
    }}/>
