### ISSUE TITLE
Is UMD build is also available 

### ISSUE THREAD

**Issue by mayanksahai** [react-component/table#97]
i am in middle of trying this out . is there any umd build available so that i can directly import it inside <script> tag and make use of it.

**Comment by yesmeck** [comment]
Sorry, we don't provide UMD build currently.

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/rc-tools/issues/16

**Comment by benjycui** [comment]
https://github.com/react-component/rc-tools/issues/16

**Comment by yesmeck** [comment]
5.2.1 has included UMD build.
