### ISSUE TITLE
设置 Sticky 后的列宽问题

### ISSUE THREAD

**Issue by willwu9304** [react-component/table#976]
在设置了 sticky，且列宽没有指定的前提下，期望 table 表头能够不显示省略号。

复现地址见：https://codesandbox.io/s/autumn-paper-f9fode?file=/src/App.js

注意 address1111111 这列显示了省略号。看了下源码，大概是因为 header table 会去监听 body table 单元格的宽度变化，从而调整自身宽度。是否能够反过来 header 影响 body 的单元格宽度呢？

**Comment by Lpbzzz** [comment]
> 在设置了 sticky，且列宽没有指定的前提下，期望 table 表头能够不显示省略号。
> 
> 复现地址见：https://codesandbox.io/s/autumn-paper-f9fode?file=/src/App.js
> 
> 注意 address1111111 这列显示了省略号。看了下源码，大概是因为 header table 会去监听 body table 单元格的宽度变化，从而调整自身宽度。是否能够反过来 header 影响 body 的单元格宽度呢？

嗨，你那有什么好办法了吗？我这里有个办法兼容：虚拟一个span来计算title会占多少宽度，然后加上padding+margin的值，在render的时候给render return 添加一个 div，宽度设置为之前计算出的数值。官方好像没有解决过这个问题，据说和tableLayout有关  https://github.com/ant-design/ant-design/issues/48539#issuecomment-2065835474
